services:
  postgres:
    container_name: postgres-sql-bookhub
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: bookhub
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - spring-project
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bookhub
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
networks:
  spring-project:
    driver: bridge

volumes:
  postgres:
    driver: local