services:
  postgres:
    container_name: postgres-sql-bookhub
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: bookhub
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-project
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bookhub
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-project
  keycloak:
    container_name: keycloak-bookhub
    image: quay.io/keycloak/keycloak:25.0.6
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-project
    command:
      - "start-dev"
networks:
  spring-project:
    driver: bridge

volumes:
  postgres:
    driver: local
