services:
  postgres:
    container_name: postgres-sql-bookhub
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: bookhub
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-project
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bookhub
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  bookhub-api:
    container_name: bookhub-api
    image: bookhub/bookhub:1.0.1
    ports:
      - "8088:8088"
    networks:
      - spring-project
    depends_on:
      - postgres
  bookhub-ui:
    container_name: bookhub-ui
    image: bookhub/bookhub-ui:1.0.1
    ports:
      - "8080:80"
    networks:
      - spring-project
    depends_on:
      - bookhub-api
networks:
  spring-project:
    driver: bridge

volumes:
  postgres:
    driver: local
