spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookhub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: changeme
    port: 465
    username: changeme
    password: changeme
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enabled: true
      protocol: smtp
application:
  security:
    jwt:
      secret-key: rL2hD1lvsyMA5kFqXklt8npMEikMd+Hb4c7gB1ZRpJ4=
      expiration: 8640000
  mailing:
    frontend:
      activation.url: http://localhost:4200/activate-account
  file:
    upload:
      images-directory: ./uploads
server:
  port: 8088
